from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from optimization_infra.plan_candidate_run import load_structured, write_yaml


def create_observations(
    *,
    run_id: str,
    parent_run_id: str | None,
    changed_parameters: list[dict[str, Any]],
    baseline_metrics: dict[str, float],
    candidate_metrics: dict[str, float],
    execution_plan: dict[str, Any],
    objective_metric: str = "expected_significance",
) -> dict[str, Any]:
    baseline_value = baseline_metrics.get(objective_metric)
    candidate_value = candidate_metrics.get(objective_metric)
    absolute = None if baseline_value is None or candidate_value is None else candidate_value - baseline_value
    relative = None if not baseline_value or absolute is None else absolute / baseline_value
    failed = execution_plan.get("status") == "blocked" or bool(execution_plan.get("invariant_violations"))
    if failed:
        status = "invalid candidate"
    elif absolute is None:
        status = "ambiguous result"
    elif abs(absolute) < 1e-12:
        status = "negligible change"
    elif absolute > 0:
        status = "credible improvement"
    else:
        status = "credible deterioration"

    return {
        "run_id": run_id,
        "parent_run_id": parent_run_id,
        "configuration_changes": {
            "changed_parameters": changed_parameters,
            "rationale": "Infrastructure-generated observation summary.",
            "change_mode": "quantitative_local",
        },
        "primary_metric_response": {
            "metric": objective_metric,
            "baseline_value": baseline_value,
            "candidate_value": candidate_value,
            "absolute_change": absolute,
            "relative_change": relative,
            "uncertainty": candidate_metrics.get(f"{objective_metric}_uncertainty"),
            "meaningfulness": "not_assessed_without_domain_threshold",
        },
        "yield_cutflow_response": {
            "yield_changes": [],
            "cutflow_changes": [],
            "signal_background_pattern": "not_available",
            "unexpected_empty_or_unstable_categories": [],
        },
        "shape_response": {
            "changed_distributions": [],
            "localized_or_global": "not_available",
            "suspicious_structures": [],
            "binning_assessment": "not_available",
        },
        "fit_inference_response": {
            "parameter_changes": [],
            "nuisance_changes": [],
            "goodness_of_fit_changes": [],
            "uncertainty_changes": [],
            "dominant_categories": [],
        },
        "validation_response": {
            "verifier_results": execution_plan.get("status"),
            "warnings": execution_plan.get("invariant_violations", []),
            "failed_checks": execution_plan.get("invariant_violations", []),
            "artifacts_reused": execution_plan.get("reused_artifacts", []),
            "stages_rerun": [s["stage_id"] for s in execution_plan.get("stages", []) if s["decision"] == "rerun"],
            "cache_concerns": [],
        },
        "interpretation": {
            "status": status,
            "direct_observations": [],
            "plausible_interpretation": "No domain interpretation generated by infrastructure-only tooling.",
            "unresolved_uncertainty": ["Domain thresholds for practical meaningfulness are not defined."],
            "possible_implementation_issue": failed,
        },
    }


def summarize_scan(scan_id: str, observation_paths: list[str | Path], runs_dir: str | Path = "runs") -> dict[str, Any]:
    observations = [load_structured(path) for path in observation_paths]
    metric_rows = []
    for obs in observations:
        metric = obs.get("primary_metric_response", {})
        metric_rows.append(
            {
                "run_id": obs.get("run_id"),
                "candidate_value": metric.get("candidate_value"),
                "absolute_change": metric.get("absolute_change"),
                "status": obs.get("interpretation", {}).get("status"),
            }
        )
    valid_rows = [row for row in metric_rows if isinstance(row.get("candidate_value"), (int, float))]
    best = max(valid_rows, key=lambda row: row["candidate_value"]) if valid_rows else None
    summary = {
        "scan_id": scan_id,
        "what_was_scanned": "See candidate observation configuration changes.",
        "why_scanned": "Infrastructure summary; scientific rationale should be supplied by scan spec or human note.",
        "artifacts_reused": sorted({a for obs in observations for a in obs.get("validation_response", {}).get("artifacts_reused", [])}),
        "stages_rerun": sorted({s for obs in observations for s in obs.get("validation_response", {}).get("stages_rerun", [])}),
        "best_candidate": best,
        "optimum_character": "inconclusive_without_dense_metric_series",
        "improvements": [row for row in metric_rows if row.get("status") == "credible improvement"],
        "deteriorations": [row for row in metric_rows if row.get("status") == "credible deterioration"],
        "verifier_failures": [row for row in metric_rows if row.get("status") == "invalid candidate"],
        "suspicious_candidates": [row for row in metric_rows if row.get("status") == "suspicious improvement"],
        "next_decision": "requires_human_or_reasoning_agent_if_pattern_is_unclear",
        "observations": metric_rows,
    }
    scan_dir = Path(runs_dir) / scan_id
    write_yaml(scan_dir / "scan_summary.yaml", summary)
    (scan_dir / "SCAN_SUMMARY.md").write_text(render_scan_summary_markdown(summary))
    return summary


def render_scan_summary_markdown(summary: dict[str, Any]) -> str:
    lines = [
        f"# Scan Summary: {summary['scan_id']}",
        "",
        f"What was scanned: {summary['what_was_scanned']}",
        f"Optimum character: `{summary['optimum_character']}`",
        "",
        "## Candidates",
    ]
    for row in summary["observations"]:
        lines.append(f"- `{row['run_id']}`: value `{row['candidate_value']}`, change `{row['absolute_change']}`, status `{row['status']}`")
    lines.extend(["", f"Next decision: `{summary['next_decision']}`", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize observation files for one scan.")
    parser.add_argument("--scan-id", required=True)
    parser.add_argument("--observation", action="append", required=True)
    parser.add_argument("--runs-dir", default="runs")
    args = parser.parse_args()
    summary = summarize_scan(args.scan_id, args.observation, args.runs_dir)
    print(yaml.safe_dump(summary, sort_keys=False))


if __name__ == "__main__":
    main()
